// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Repositories.DbContexts
{
    public partial class WebApiDbContext
    {
        public virtual DbSet<SysAttachment> SysAttachments { get; set; }
        public virtual DbSet<SysButton> SysButtons { get; set; }
        public virtual DbSet<SysButtonpermission> SysButtonpermissions { get; set; }
        public virtual DbSet<SysDictionary> SysDictionarys { get; set; }
        public virtual DbSet<SysEmailqueue> SysEmailqueues { get; set; }
        public virtual DbSet<SysLog> SysLogs { get; set; }
        public virtual DbSet<SysMenupermission> SysMenupermissions { get; set; }
        public virtual DbSet<SysOrg> SysOrgs { get; set; }
        public virtual DbSet<SysPermissiondelegation> SysPermissiondelegations { get; set; }
        public virtual DbSet<SysReportline> SysReportlines { get; set; }
        public virtual DbSet<SysRole> SysRoles { get; set; }
        public virtual DbSet<SysRoute> SysRoutes { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<SysUserroleorg> SysUserroleorgs { get; set; }
    }
}
