// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 菜单权限表
/// </summary>
public partial class sys_menupermission
{
    /// <summary>
    /// 主键
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 菜单Code
    /// </summary>
    public Guid RouteCode { get; set; }

    /// <summary>
    /// 授权主体类型：User, Role, Org
    /// </summary>
    public string SubjectType { get; set; }

    /// <summary>
    /// 主体Code（用户Code/角色Code/组织Code）
    /// </summary>
    public Guid SubjectCode { get; set; }

    /// <summary>
    /// 是否授权
    /// </summary>
    public ulong IsGranted { get; set; }

    public ulong IsDelete { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? CreateUserCode { get; set; }

    public DateTime? ModifyTime { get; set; }

    public Guid? ModifyUserCode { get; set; }
}
