// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 通用附件表
/// </summary>
public partial class sys_attachment
{
    /// <summary>
    /// 主键 UUID
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 文件名（含扩展名）
    /// </summary>
    public string FileName { get; set; }

    /// <summary>
    /// 文件扩展名
    /// </summary>
    public string FileExtension { get; set; }

    /// <summary>
    /// 文件原名
    /// </summary>
    public string FileClientName { get; set; }

    /// <summary>
    /// 完整存储路径（如OSS路径）
    /// </summary>
    public string FilePath { get; set; }

    /// <summary>
    /// 文件MIME类型（如 image/png）
    /// </summary>
    public string FileType { get; set; }

    /// <summary>
    /// 文件大小（字节）
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// 文件MD5校验值（32位十六进制）
    /// </summary>
    public string MD5Hash { get; set; }

    /// <summary>
    /// 下载次数
    /// </summary>
    public int? DownloadCount { get; set; }

    /// <summary>
    /// 文件描述
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 业务实体类型（如 ApplicationForm, Order）
    /// </summary>
    public string EntityType { get; set; }

    /// <summary>
    /// 关联的业务实体Code
    /// </summary>
    public Guid EntityCode { get; set; }

    /// <summary>
    /// 是否启用
    /// </summary>
    public ulong IsEnable { get; set; }

    /// <summary>
    /// 软删除
    /// </summary>
    public ulong IsDelete { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 创建人Code
    /// </summary>
    public Guid? CreateUserCode { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    public DateTime? ModifyTime { get; set; }

    /// <summary>
    /// 修改人Code
    /// </summary>
    public Guid? ModifyUserCode { get; set; }
}
