// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 用户表
/// </summary>
public partial class sys_user
{
    /// <summary>
    /// 主键 UUID
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 登录账号
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 用户全名
    /// </summary>
    public string FullName { get; set; }

    /// <summary>
    /// 密码（加密）
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 手机号
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// 是否活动
    /// </summary>
    public ulong? IsActive { get; set; }

    /// <summary>
    /// 是否启用
    /// </summary>
    public ulong IsEnable { get; set; }

    /// <summary>
    /// 软删除
    /// </summary>
    public ulong IsDelete { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 创建人Code
    /// </summary>
    public Guid? CreateUserCode { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    public DateTime? ModifyTime { get; set; }

    /// <summary>
    /// 修改人Code
    /// </summary>
    public Guid? ModifyUserCode { get; set; }
}
