// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 组织架构表
/// </summary>
public partial class sys_org
{
    /// <summary>
    /// 主键
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 父级组织Code
    /// </summary>
    public Guid? ParentCode { get; set; }

    /// <summary>
    /// 组织名称
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 组织类型：公司、本部、部、课、班、组、虚拟组
    /// </summary>
    public string OrgType { get; set; }

    /// <summary>
    /// 路径（如 /公司/本部/部/课）
    /// </summary>
    public string Path { get; set; }

    /// <summary>
    /// 层级深度
    /// </summary>
    public int Level { get; set; }

    /// <summary>
    /// 排序号
    /// </summary>
    public int Sort { get; set; }

    /// <summary>
    /// 是否虚拟组
    /// </summary>
    public ulong IsVirtual { get; set; }

    public ulong IsEnable { get; set; }

    public ulong IsDelete { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? CreateUserCode { get; set; }

    public DateTime? ModifyTime { get; set; }

    public Guid? ModifyUserCode { get; set; }
}
