// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 用户角色分配表
/// </summary>
public partial class sys_userroleorg
{
    /// <summary>
    /// 主键
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 用户Code
    /// </summary>
    public Guid UserCode { get; set; }

    /// <summary>
    /// 角色Code
    /// </summary>
    public Guid RoleCode { get; set; }

    /// <summary>
    /// 任职组织Code
    /// </summary>
    public Guid OrgCode { get; set; }

    /// <summary>
    /// 是否主要角色
    /// </summary>
    public ulong IsPrimary { get; set; }

    public ulong IsEnable { get; set; }

    public ulong IsDelete { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? CreateUserCode { get; set; }

    public DateTime? ModifyTime { get; set; }

    public Guid? ModifyUserCode { get; set; }
}
