// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 字典表
/// </summary>
public partial class sys_dictionary
{
    /// <summary>
    /// 主键 UUID
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 父级字典Code
    /// </summary>
    public Guid? ParentCode { get; set; }

    /// <summary>
    /// 字典类别
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 键
    /// </summary>
    public string KeyText { get; set; }

    /// <summary>
    /// 值
    /// </summary>
    public string ValueText { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int Sort { get; set; }

    /// <summary>
    /// 是否启用
    /// </summary>
    public ulong IsEnable { get; set; }

    /// <summary>
    /// 软删除
    /// </summary>
    public ulong IsDelete { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 创建人Code
    /// </summary>
    public Guid? CreateUserCode { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    public DateTime? ModifyTime { get; set; }

    /// <summary>
    /// 修改人Code
    /// </summary>
    public Guid? ModifyUserCode { get; set; }
}
