// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Domain.Entities;

/// <summary>
/// 权限委托表（用于权限下放）
/// </summary>
public partial class sys_permissiondelegation
{
    /// <summary>
    /// 主键 UUID
    /// </summary>
    public Guid Code { get; set; }

    /// <summary>
    /// 授权人（委托方）用户Code
    /// </summary>
    public Guid FromUserCode { get; set; }

    /// <summary>
    /// 被授权人（受托方）用户Code
    /// </summary>
    public Guid ToUserCode { get; set; }

    /// <summary>
    /// 下放的按钮Code（关联 SYS_Button）
    /// </summary>
    public Guid ButtonCode { get; set; }

    /// <summary>
    /// 限定菜单Code（可为空，表示该按钮下所有菜单实例）
    /// </summary>
    public Guid? RouteCode { get; set; }

    /// <summary>
    /// 附加条件，JSON格式，如 {&quot;DepartmentCode&quot;: &quot;xxx&quot;, &quot;Amount&quot;: {&quot;$lte&quot;: 10000}}
    /// </summary>
    public string Condition { get; set; }

    /// <summary>
    /// 生效开始时间
    /// </summary>
    public DateTime EffectiveStartDate { get; set; }

    /// <summary>
    /// 生效结束时间
    /// </summary>
    public DateTime EffectiveEndDate { get; set; }

    /// <summary>
    /// 是否启用
    /// </summary>
    public ulong IsActive { get; set; }

    /// <summary>
    /// 软删除
    /// </summary>
    public ulong IsDelete { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? CreateUserCode { get; set; }

    public DateTime? ModifyTime { get; set; }

    public Guid? ModifyUserCode { get; set; }
}
