// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Interface.IAggregateRoots;

namespace Domain.Entities;

/// <summary>
/// 按钮表
/// </summary>
public partial class SysButton : Entity, IAggregateRoot
{
    /// <summary>
    /// 按钮唯一标识（如 Add, Edit）
    /// </summary>
    public string ButtonKey { get; set; }

    /// <summary>
    /// 所属菜单Code
    /// </summary>
    public Guid RouteCode { get; set; }

    /// <summary>
    /// 按钮显示文字
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 前端触发事件名称（如 handleAdd）
    /// </summary>
    public string Event { get; set; }

    /// <summary>
    /// 按钮样式：primary, success, warning, danger, info
    /// </summary>
    public string StyleType { get; set; }

    /// <summary>
    /// 按钮类型：1-普通按钮，2-选中时按钮
    /// </summary>
    public int Type { get; set; }

    /// <summary>
    /// 按钮图标
    /// </summary>
    public string Icon { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int? Sort { get; set; }

    /// <summary>
    /// 是否系统内置按钮
    /// </summary>
    public ulong IsSystemButton { get; set; }
}
