// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 字典表
/// </summary>
public partial class SysDictionary : Entity, IAggregateRoot
{
    /// <summary>
    /// 父级字典Code
    /// </summary>
    public Guid? ParentCode { get; set; }

    /// <summary>
    /// 字典类别
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 键
    /// </summary>
    public string KeyText { get; set; }

    /// <summary>
    /// 值
    /// </summary>
    public string ValueText { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int Sort { get; set; }
}