// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Interface.IAggregateRoots;

namespace Domain.Entities;

/// <summary>
/// 邮件发送队列表
/// </summary>
public partial class SysEmailqueue : Entity, IAggregateRoot
{
    /// <summary>
    /// 邮件编号
    /// </summary>
    public string EmailCode { get; set; }

    /// <summary>
    /// 邮件标题
    /// </summary>
    public string Subject { get; set; }

    /// <summary>
    /// 邮件内容（支持HTML）
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 收件人，多个邮箱使用 ; 分隔
    /// </summary>
    public string ToAddress { get; set; }

    /// <summary>
    /// 抄送人
    /// </summary>
    public string CcAddress { get; set; }

    /// <summary>
    /// 密送人
    /// </summary>
    public string BccAddress { get; set; }

    /// <summary>
    /// 是否HTML格式
    /// </summary>
    public ulong IsBodyHtml { get; set; }

    /// <summary>
    /// 发送状态：0待发送 1发送中 2发送成功 3发送失败
    /// </summary>
    public int SendStatus { get; set; }

    /// <summary>
    /// 重试次数
    /// </summary>
    public int RetryCount { get; set; }

    /// <summary>
    /// 最大重试次数
    /// </summary>
    public int MaxRetryCount { get; set; }

    /// <summary>
    /// 实际发送时间
    /// </summary>
    public DateTime? SentTime { get; set; }

    /// <summary>
    /// 错误信息
    /// </summary>
    public string ErrorMessage { get; set; }

    /// <summary>
    /// 业务类型
    /// </summary>
    public string BusinessType { get; set; }

    /// <summary>
    /// 业务ID
    /// </summary>
    public string BusinessId { get; set; }

    /// <summary>
    /// 备注
    /// </summary>
    public string Remark { get; set; }
}
