// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 通用日志表
/// </summary>
public partial class SysLog : Entity, IAggregateRoot
{
    /// <summary>
    /// 操作用户名
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 日志类型：Request(网络日志)、System(系统日志)、User(用户操作日志)、Security(安全日志)
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 菜单名称
    /// </summary>
    public string MenuName { get; set; }

    /// <summary>
    /// 模块名称
    /// </summary>
    public string ModuleName { get; set; }

    /// <summary>
    /// 按钮名称
    /// </summary>
    public string ButtonName { get; set; }

    /// <summary>
    /// 操作内容
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 操作结果
    /// </summary>
    public string Result { get; set; }

    /// <summary>
    /// 请求链接
    /// </summary>
    public string Url { get; set; }

    /// <summary>
    /// 请求IP
    /// </summary>
    public string Ip { get; set; }

    /// <summary>
    /// 工作站名称
    /// </summary>
    public string WorkStationName { get; set; }

    /// <summary>
    /// 请求方法（GET/POST等）
    /// </summary>
    public string Method { get; set; }

    /// <summary>
    /// 请求参数
    /// </summary>
    public string Params { get; set; }
}
