// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 角色表
/// </summary>
public partial class SysRole : Entity, IAggregateRoot
{
    /// <summary>
    /// 角色名称
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 默认上级角色Code（自引用，用于汇报链）
    /// </summary>
    public Guid? SuperiorRoleCode { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// 角色层级数值（数值越小越低）
    /// </summary>
    public int Level { get; set; }
}
