// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 指定汇报关系表
/// </summary>
public partial class SysReportline : Entity, IAggregateRoot
{
    /// <summary>
    /// 员工用户Code
    /// </summary>
    public Guid UserCode { get; set; }

    /// <summary>
    /// 直接上级用户Code
    /// </summary>
    public Guid SupervisorUserCode { get; set; }

    /// <summary>
    /// 所在组织Code
    /// </summary>
    public Guid OrgCode { get; set; }

    /// <summary>
    /// 担任的角色Code（冗余）
    /// </summary>
    public Guid? RoleCode { get; set; }

    public ulong IsActive { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }
}
