// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Interface.IAggregateRoots;

namespace Domain.Entities;

/// <summary>
/// 菜单表
/// </summary>
public partial class SysRoute : Entity, IAggregateRoot
{
    /// <summary>
    /// 父菜单Code
    /// </summary>
    public Guid? ParentCode { get; set; }

    /// <summary>
    /// 路由路径（支持动态参数）
    /// </summary>
    public string Path { get; set; }

    /// <summary>
    /// 组件路径（如 views/user/index）
    /// </summary>
    public string Component { get; set; }

    /// <summary>
    /// 菜单名称（用于路由命名）
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 重定向路径
    /// </summary>
    public string Redirect { get; set; }

    /// <summary>
    /// 是否隐藏菜单
    /// </summary>
    public ulong Hidden { get; set; }

    /// <summary>
    /// 是否始终显示父菜单
    /// </summary>
    public ulong AlwaysShow { get; set; }

    /// <summary>
    /// 菜单显示标题（支持国际化）
    /// </summary>
    public string MetaTitle { get; set; }

    /// <summary>
    /// 菜单图标（Element Plus 图标名）
    /// </summary>
    public string MetaIcon { get; set; }

    /// <summary>
    /// 是否不缓存页面
    /// </summary>
    public ulong MetaNoCache { get; set; }

    /// <summary>
    /// 是否固定标签页
    /// </summary>
    public ulong MetaAffix { get; set; }

    /// <summary>
    /// 高亮菜单路径
    /// </summary>
    public string MetaActiveMenu { get; set; }

    /// <summary>
    /// 排序号
    /// </summary>
    public int Sort { get; set; }
}
