// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 用户角色分配表
/// </summary>
public partial class SysUserroleorg : Entity, IAggregateRoot
{
    /// <summary>
    /// 用户Code
    /// </summary>
    public Guid UserCode { get; set; }

    /// <summary>
    /// 角色Code
    /// </summary>
    public Guid RoleCode { get; set; }

    /// <summary>
    /// 任职组织Code
    /// </summary>
    public Guid OrgCode { get; set; }

    /// <summary>
    /// 是否主要角色
    /// </summary>
    public ulong IsPrimary { get; set; }
}
