// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using Domain.Base;

namespace Domain.Entities;

/// <summary>
/// 用户表
/// </summary>
public partial class SysUser : Entity, IAggregateRoot
{
    /// <summary>
    /// 登录账号
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 用户全名
    /// </summary>
    public string FullName { get; set; }

    /// <summary>
    /// 密码（加密）
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// APO账号
    /// </summary>
    public string Apo { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 手机号
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// 座机
    /// </summary>
    public string Tel { get; set; }

    /// <summary>
    /// 生日
    /// </summary>
    public DateTime? DateOfBirth { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    public int? Sex { get; set; }

    /// <summary>
    /// 证件类型
    /// </summary>
    public int? DocumentType { get; set; }

    /// <summary>
    /// 证件号码
    /// </summary>
    public string DocumentNumber { get; set; }

    /// <summary>
    /// 最后登录时间
    /// </summary>
    public DateTime? LastLoginTime { get; set; }

    /// <summary>
    /// 登录失败计次
    /// </summary>
    public int? FailedLoginCount { get; set; }

    /// <summary>
    /// 是否已锁定
    /// </summary>
    public ulong? IsLocked { get; set; }

    /// <summary>
    /// 锁定结束时间
    /// </summary>
    public DateTime? LockEndTime { get; set; }

    /// <summary>
    /// 最后修改密码时间
    /// </summary>
    public DateTime? PasswordLastSetTime { get; set; }

    /// <summary>
    /// 最近的密码
    /// </summary>
    public string LastFewPasswords { get; set; }

    /// <summary>
    /// 是否活动
    /// </summary>
    public ulong? IsActive { get; set; }
}
