// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class testContext : DbContext
{
    public testContext(DbContextOptions<testContext> options)
        : base(options)
    {
    }

    public virtual DbSet<sys_attachment> sys_attachment { get; set; }

    public virtual DbSet<sys_button> sys_button { get; set; }

    public virtual DbSet<sys_buttonpermission> sys_buttonpermission { get; set; }

    public virtual DbSet<sys_dictionary> sys_dictionary { get; set; }

    public virtual DbSet<sys_emailqueue> sys_emailqueue { get; set; }

    public virtual DbSet<sys_log> sys_log { get; set; }

    public virtual DbSet<sys_menupermission> sys_menupermission { get; set; }

    public virtual DbSet<sys_org> sys_org { get; set; }

    public virtual DbSet<sys_permissiondelegation> sys_permissiondelegation { get; set; }

    public virtual DbSet<sys_reportline> sys_reportline { get; set; }

    public virtual DbSet<sys_role> sys_role { get; set; }

    public virtual DbSet<sys_route> sys_route { get; set; }

    public virtual DbSet<sys_user> sys_user { get; set; }

    public virtual DbSet<sys_userroleorg> sys_userroleorg { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<sys_attachment>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("通用附件表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => new { e.EntityType, e.EntityCode }, "idx_entity");

            entity.HasIndex(e => e.IsDelete, "idx_isdelete");

            entity.HasIndex(e => e.MD5Hash, "idx_md5hash");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.CreateTime)
                .HasComment("创建时间")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateUserCode).HasComment("创建人Code");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasComment("文件描述");
            entity.Property(e => e.DownloadCount)
                .HasDefaultValueSql("'0'")
                .HasComment("下载次数");
            entity.Property(e => e.EntityCode).HasComment("关联的业务实体Code");
            entity.Property(e => e.EntityType)
                .HasMaxLength(100)
                .HasComment("业务实体类型（如 ApplicationForm, Order）");
            entity.Property(e => e.FileClientName)
                .HasMaxLength(500)
                .HasComment("文件原名");
            entity.Property(e => e.FileExtension)
                .HasMaxLength(50)
                .HasComment("文件扩展名");
            entity.Property(e => e.FileName)
                .HasMaxLength(500)
                .HasComment("文件名（含扩展名）");
            entity.Property(e => e.FilePath)
                .HasMaxLength(1000)
                .HasComment("完整存储路径（如OSS路径）");
            entity.Property(e => e.FileSize).HasComment("文件大小（字节）");
            entity.Property(e => e.FileType)
                .HasMaxLength(100)
                .HasComment("文件MIME类型（如 image/png）");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MD5Hash)
                .HasMaxLength(32)
                .HasComment("文件MD5校验值（32位十六进制）");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifyUserCode).HasComment("修改人Code");
        });

        modelBuilder.Entity<sys_button>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("按钮表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.RouteCode, "idx_routecode");

            entity.HasIndex(e => new { e.ButtonKey, e.RouteCode }, "uk_buttonkey_route").IsUnique();

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.ButtonKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("按钮唯一标识（如 Add, Edit）");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.Event)
                .HasMaxLength(100)
                .HasComment("前端触发事件名称（如 handleAdd）");
            entity.Property(e => e.Icon)
                .HasMaxLength(50)
                .HasComment("按钮图标");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsSystemButton)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否系统内置按钮")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("按钮显示文字");
            entity.Property(e => e.RouteCode).HasComment("所属菜单Code");
            entity.Property(e => e.Sort)
                .HasDefaultValueSql("'0'")
                .HasComment("排序");
            entity.Property(e => e.StyleType)
                .HasMaxLength(20)
                .HasDefaultValueSql("'default'")
                .HasComment("按钮样式：primary, success, warning, danger, info");
            entity.Property(e => e.Type)
                .HasDefaultValueSql("'1'")
                .HasComment("按钮类型：1-普通按钮，2-选中时按钮");
        });

        modelBuilder.Entity<sys_buttonpermission>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("按钮权限表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => new { e.SubjectType, e.SubjectCode }, "idx_subject");

            entity.HasIndex(e => new { e.ButtonCode, e.SubjectType, e.SubjectCode }, "uk_button_subject").IsUnique();

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.ButtonCode).HasComment("按钮Code");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsGranted)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否授权")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.SubjectCode).HasComment("主体Code");
            entity.Property(e => e.SubjectType)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("授权主体类型：User, Role, Org");
        });

        modelBuilder.Entity<sys_dictionary>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("字典表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.IsDelete, "idx_isdelete");

            entity.HasIndex(e => e.KeyText, "idx_keytext");

            entity.HasIndex(e => e.ParentCode, "idx_parentcode");

            entity.HasIndex(e => e.Type, "idx_type");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.CreateTime)
                .HasComment("创建时间")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateUserCode).HasComment("创建人Code");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasComment("描述");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.KeyText)
                .HasMaxLength(100)
                .HasComment("键");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifyUserCode).HasComment("修改人Code");
            entity.Property(e => e.ParentCode).HasComment("父级字典Code");
            entity.Property(e => e.Sort).HasComment("排序");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasComment("字典类别");
            entity.Property(e => e.ValueText)
                .HasMaxLength(500)
                .HasComment("值");
        });

        modelBuilder.Entity<sys_emailqueue>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("邮件发送队列表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.BusinessId, "idx_businessid");

            entity.HasIndex(e => e.BusinessType, "idx_businesstype");

            entity.HasIndex(e => e.CreateTime, "idx_createtime");

            entity.HasIndex(e => e.EmailCode, "idx_emailcode");

            entity.HasIndex(e => e.IsDelete, "idx_isdelete");

            entity.HasIndex(e => e.SendStatus, "idx_sendstatus");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.BccAddress)
                .HasMaxLength(1000)
                .HasComment("密送人");
            entity.Property(e => e.BusinessId)
                .HasMaxLength(100)
                .HasComment("业务ID");
            entity.Property(e => e.BusinessType)
                .HasMaxLength(100)
                .HasComment("业务类型");
            entity.Property(e => e.CcAddress)
                .HasMaxLength(1000)
                .HasComment("抄送人");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasComment("邮件内容（支持HTML）");
            entity.Property(e => e.CreateTime)
                .HasComment("创建时间")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateUserCode).HasComment("创建人Code");
            entity.Property(e => e.EmailCode)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("邮件编号");
            entity.Property(e => e.ErrorMessage)
                .HasComment("错误信息")
                .HasColumnType("text");
            entity.Property(e => e.IsBodyHtml)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否HTML格式")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MaxRetryCount)
                .HasDefaultValueSql("'5'")
                .HasComment("最大重试次数");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifyUserCode).HasComment("修改人Code");
            entity.Property(e => e.Remark)
                .HasMaxLength(500)
                .HasComment("备注");
            entity.Property(e => e.RetryCount).HasComment("重试次数");
            entity.Property(e => e.SendStatus).HasComment("发送状态：0待发送 1发送中 2发送成功 3发送失败");
            entity.Property(e => e.SentTime)
                .HasComment("实际发送时间")
                .HasColumnType("datetime");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(500)
                .HasComment("邮件标题");
            entity.Property(e => e.ToAddress)
                .IsRequired()
                .HasMaxLength(1000)
                .HasComment("收件人，多个邮箱使用 ; 分隔");
        });

        modelBuilder.Entity<sys_log>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("通用日志表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.CreateTime, "idx_createtime");

            entity.HasIndex(e => e.IP, "idx_ip");

            entity.HasIndex(e => e.IsDelete, "idx_isdelete");

            entity.HasIndex(e => e.Type, "idx_type");

            entity.HasIndex(e => e.UserName, "idx_username");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.ButtonName)
                .HasMaxLength(100)
                .HasComment("按钮名称");
            entity.Property(e => e.Content)
                .HasComment("操作内容")
                .HasColumnType("text");
            entity.Property(e => e.CreateTime)
                .HasComment("创建时间（日志发生时间）")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateUserCode).HasComment("创建人Code（冗余）");
            entity.Property(e => e.IP)
                .HasMaxLength(50)
                .HasComment("请求IP");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MenuName)
                .HasMaxLength(200)
                .HasComment("菜单名称");
            entity.Property(e => e.Method)
                .HasMaxLength(10)
                .HasComment("请求方法（GET/POST等）");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifyUserCode).HasComment("修改人Code");
            entity.Property(e => e.ModuleName)
                .HasMaxLength(200)
                .HasComment("模块名称");
            entity.Property(e => e.Params)
                .HasComment("请求参数")
                .HasColumnType("text");
            entity.Property(e => e.Result)
                .HasComment("操作结果")
                .HasColumnType("text");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasComment("日志类型：Request(网络日志)、System(系统日志)、User(用户操作日志)、Security(安全日志)");
            entity.Property(e => e.Url)
                .HasMaxLength(500)
                .HasComment("请求链接");
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .HasComment("操作用户名");
            entity.Property(e => e.WorkStationName)
                .HasMaxLength(200)
                .HasComment("工作站名称");
        });

        modelBuilder.Entity<sys_menupermission>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("菜单权限表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => new { e.SubjectType, e.SubjectCode }, "idx_subject");

            entity.HasIndex(e => new { e.RouteCode, e.SubjectType, e.SubjectCode }, "uk_route_subject").IsUnique();

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsGranted)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否授权")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.RouteCode).HasComment("菜单Code");
            entity.Property(e => e.SubjectCode).HasComment("主体Code（用户Code/角色Code/组织Code）");
            entity.Property(e => e.SubjectType)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("授权主体类型：User, Role, Org");
        });

        modelBuilder.Entity<sys_org>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("组织架构表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.ParentCode, "idx_parentcode");

            entity.HasIndex(e => e.Path, "idx_path").HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsVirtual)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否虚拟组")
                .HasColumnType("bit(1)");
            entity.Property(e => e.Level).HasComment("层级深度");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasComment("组织名称");
            entity.Property(e => e.OrgType)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("组织类型：公司、本部、部、课、班、组、虚拟组");
            entity.Property(e => e.ParentCode).HasComment("父级组织Code");
            entity.Property(e => e.Path)
                .HasMaxLength(1000)
                .HasComment("路径（如 /公司/本部/部/课）");
            entity.Property(e => e.Sort).HasComment("排序号");
        });

        modelBuilder.Entity<sys_permissiondelegation>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("权限委托表（用于权限下放）"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.ButtonCode, "idx_button");

            entity.HasIndex(e => new { e.EffectiveStartDate, e.EffectiveEndDate }, "idx_effectivedate");

            entity.HasIndex(e => e.FromUserCode, "idx_fromuser");

            entity.HasIndex(e => e.ToUserCode, "idx_touser");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.ButtonCode).HasComment("下放的按钮Code（关联 SYS_Button）");
            entity.Property(e => e.Condition)
                .HasComment("附加条件，JSON格式，如 {\"DepartmentCode\": \"xxx\", \"Amount\": {\"$lte\": 10000}}")
                .HasColumnType("json");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.EffectiveEndDate)
                .HasComment("生效结束时间")
                .HasColumnType("datetime");
            entity.Property(e => e.EffectiveStartDate)
                .HasComment("生效开始时间")
                .HasColumnType("datetime");
            entity.Property(e => e.FromUserCode).HasComment("授权人（委托方）用户Code");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.RouteCode).HasComment("限定菜单Code（可为空，表示该按钮下所有菜单实例）");
            entity.Property(e => e.ToUserCode).HasComment("被授权人（受托方）用户Code");
        });

        modelBuilder.Entity<sys_reportline>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("指定汇报关系表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.SupervisorUserCode, "idx_supervisor");

            entity.HasIndex(e => e.UserCode, "idx_usercode");

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.OrgCode).HasComment("所在组织Code");
            entity.Property(e => e.RoleCode).HasComment("担任的角色Code（冗余）");
            entity.Property(e => e.SupervisorUserCode).HasComment("直接上级用户Code");
            entity.Property(e => e.UserCode).HasComment("员工用户Code");
        });

        modelBuilder.Entity<sys_role>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("角色表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.SuperiorRoleCode, "idx_superior");

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.Level).HasComment("角色层级数值（数值越小越低）");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("角色名称");
            entity.Property(e => e.SuperiorRoleCode).HasComment("默认上级角色Code（自引用，用于汇报链）");
        });

        modelBuilder.Entity<sys_route>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("菜单表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.ParentCode, "idx_parentcode");

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.AlwaysShow)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否始终显示父菜单")
                .HasColumnType("bit(1)");
            entity.Property(e => e.Component)
                .HasMaxLength(255)
                .HasComment("组件路径（如 views/user/index）");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.Hidden)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否隐藏菜单")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MetaActiveMenu)
                .HasMaxLength(255)
                .HasComment("高亮菜单路径");
            entity.Property(e => e.MetaAffix)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否固定标签页")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MetaIcon)
                .HasMaxLength(50)
                .HasComment("菜单图标（Element Plus 图标名）");
            entity.Property(e => e.MetaNoCache)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否不缓存页面")
                .HasColumnType("bit(1)");
            entity.Property(e => e.MetaTitle)
                .HasMaxLength(100)
                .HasComment("菜单显示标题（支持国际化）");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("菜单名称（用于路由命名）");
            entity.Property(e => e.ParentCode).HasComment("父菜单Code");
            entity.Property(e => e.Path)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("路由路径（支持动态参数）");
            entity.Property(e => e.Redirect)
                .HasMaxLength(255)
                .HasComment("重定向路径");
            entity.Property(e => e.Sort).HasComment("排序号");
        });

        modelBuilder.Entity<sys_user>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("用户表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.IsDelete, "idx_isdelete");

            entity.HasIndex(e => e.Name, "idx_name");

            entity.Property(e => e.Code).HasComment("主键 UUID");
            entity.Property(e => e.CreateTime)
                .HasComment("创建时间")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateUserCode).HasComment("创建人Code");
            entity.Property(e => e.Email)
                .HasMaxLength(200)
                .HasComment("邮箱");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasComment("用户全名");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否活动")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasComment("软删除")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasComment("是否启用")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifyUserCode).HasComment("修改人Code");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("登录账号");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasComment("密码（加密）");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasComment("手机号");
        });

        modelBuilder.Entity<sys_userroleorg>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("PRIMARY");

            entity
                .ToTable(tb => tb.HasComment("用户角色分配表"))
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.OrgCode, "idx_orgcode");

            entity.HasIndex(e => e.RoleCode, "idx_rolecode");

            entity.HasIndex(e => e.UserCode, "idx_usercode");

            entity.HasIndex(e => new { e.UserCode, e.RoleCode, e.OrgCode }, "uk_user_role_org").IsUnique();

            entity.Property(e => e.Code).HasComment("主键");
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IsDelete)
                .HasDefaultValueSql("b'0'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsEnable)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.IsPrimary)
                .HasDefaultValueSql("b'0'")
                .HasComment("是否主要角色")
                .HasColumnType("bit(1)");
            entity.Property(e => e.ModifyTime).HasColumnType("datetime");
            entity.Property(e => e.OrgCode).HasComment("任职组织Code");
            entity.Property(e => e.RoleCode).HasComment("角色Code");
            entity.Property(e => e.UserCode).HasComment("用户Code");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
